sudo: required
dist: bionic

before_install:
  - sudo apt-get install apt-transport-https
  - wget -qO - https://packages.chef.io/chef.asc | sudo apt-key add -
  - echo "deb https://packages.chef.io/repos/apt/current bionic main" > chef-current.list
  - sudo mv chef-current.list /etc/apt/sources.list.d/
  - sudo apt-get update
  - sudo apt-get -y install chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master
    - develop

services: docker

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=default-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: 
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
